Repository deepin-community/grub2, pull requests merged in 2024-08, with the labels that each got.

#15 feat: add loong64 old-world firmware compatibility
  debian/changelog
  debian/patches/0001-grub-install-loongarch64-efi-also-install-BOOTLOONGA.patch
  debian/patches/0001-loongarch64-able-to-start-on-legacy-firmware.patch
  debian/patches/series
Labels: approved, do-not-merge/hold

#13 feat: set GRUB_DEVICE by env when root is overlayfs
  debian/changelog
  debian/patches/deepin/0002-probe-grub-device-for-overlay-as-root.patch
  debian/patches/series
Labels: approved, do-not-merge/hold, needs-ok-to-test

#14 feat: reimplement boot_counter
  debian/changelog
  debian/patches/reimplement_boot_counter.patch
  debian/patches/series
Labels: approved, do-not-merge/hold, needs-ok-to-test

#16 fix: fix boot_counter error
  debian/changelog
  debian/patches/reimplement_boot_counter.patch
Labels: needs-ok-to-test
